### ISSUE TITLE
Looks like API is not working?

### ISSUE THREAD

**Issue by PratikBurkhawala** [dr5hn/csc-website#1]
API: https://api.countrystatecity.in/v1/countries/[ciso]/states/[siso]/cities
Sending API Key but getting response as [].

**Comment by dr5hn** [comment]
@PratikBurkhawala You should replace `[ciso]` with Country iso2 Code and `[siso]` with State iso2 code.

For Ex: If you want to get cities of Country India[IN] and state Gujarat[GJ], So your URL will be like
https://api.countrystatecity.in/v1/countries/IN/states/GJ/cities

Let me know if you have any other questions.

**Comment by PratikBurkhawala** [comment]
@dr5hn Getting now the cities. Thanks for you quick reply.
