### ISSUE TITLE
Request API Key mail not delivered

### ISSUE THREAD

**Issue by ErShubhamMishra** [dr5hn/csc-website#4]
Request API Key mail not delivered for shubhammishra@cedcommerce.com

**Comment by dr5hn** [comment]
@ErShubhamMishra Hope you've read the Note carefully.
<img width="644" alt="Screenshot 2021-02-26 at 12 36 57 PM" src="https://user-images.githubusercontent.com/6929121/109267347-6ba98580-782f-11eb-9a19-2a7cf6d825f4.png">
